refactor(bin): pass fixed filename to `ics-fix`

diff --git a/bin/bin/ics-fix b/bin/bin/ics-fix
--- a/bin/bin/ics-fix
+++ b/bin/bin/ics-fix
@@ -2,6 +2,12 @@
 set -eEuo pipefail
 
 FILE="$1"
+FIXED_FILE="$2"
+
+if [[ -z "$FIXED_FILE" ]]; then
+  echo "Second param for file location to save to is required!"
+  exit 1
+fi
 
 cat $FILE \
   | iconv -f UTF-16 -t UTF-8 \
@@ -9,4 +15,6 @@ cat $FILE \
   | sed 's/\x0//g' \
   | sed 's/\r\n$/\n/g' \
   | sed 's/\s$//g' \
-  | tee fixed.ics
+  > "$FIXED_FILE"
+
+rm "$FILE"
